sudo: required
services:
  - docker

before_install:
  - docker build -t reboxyz/react -f './client/Dockerfile.dev' .
  

script:
  - docker run -e CI=true reboxyz/react-test1 npm test

after_sucess:
  - docker build -t reboxyz/multi-client ./client
  - docker build -t reboxyz/multi-nginx ./nginx
  - docker build -t reboxyz/multi-server ./server
  - docker build -t reboxyz/multi-worker ./worker
  # Log in to the docker CLI   Note! Use pipe which echo output becomes standard input
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push reboxyz/multi-client
  - docker push reboxyz/multi-nginx
  - docker push reboxyz/multi-server
  - docker push reboxyz/multi-worker